In [1]:
# CB: Some qubit basics representated in LaTeX and numpy. (You need to learn LaTeX.)
# CB: This is NOT comprehensive in any way.  Just a starting place.
# CB: The Nielsen and Chuang book is the standard textbook to reference.
# CB: Note: If writing Dirac notation in a TeX document, please use the braket package!
import numpy as np

## LaTeX qubits

In [3]:
%%latex
These are the computational basis state vectors of 
a two dimensional vector space $V = \mathbf{C}^2$, the space where a qubit lives.
$$|0\rangle = \begin{bmatrix}
1 \\
0 \\
\end{bmatrix}$$

$$|1\rangle = \begin{bmatrix}
0 \\
1 \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [4]:
%%latex

The state of a qubit, written in the computational basis, with complex coefficients $\alpha$ and $\beta$.

$$|\psi\rangle = \alpha|0\rangle + \beta|1\rangle = \begin{bmatrix}
\alpha \\
0 \\
\end{bmatrix} + \begin{bmatrix}
0 \\
\beta \\
\end{bmatrix} = \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [5]:
%%latex

Conjugate transpose of state vector
$$\langle \psi | = \alpha^*\langle 0| + \beta^*\langle 1| = \begin{bmatrix}
\alpha^* & 0
\end{bmatrix} + \begin{bmatrix}
0 & \beta^*
\end{bmatrix} = \begin{bmatrix}
\alpha^* & \beta^*
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [7]:
%%latex

Tensor product $\otimes$.  (See N&C p. 74.)  AKA Kronecker product.

Each element in $\mathbf{A}$ times $\mathbf{B}$, Ex: 2 by 1 kron 2 by 1 = 4 by 1.  
    
$$|0\rangle \otimes |0\rangle = |0\rangle|0\rangle = |00\rangle = \begin{bmatrix}
1 \\
0 \\
\end{bmatrix} \otimes \begin{bmatrix}
1 \\
0 \\
\end{bmatrix} = \begin{bmatrix}
1 \\
0 \\
0 \\
0 \\
\end{bmatrix}$$

Exercise: work out $|1\rangle \otimes |1\rangle$


<IPython.core.display.Latex object>

In [9]:
%%latex
Another example:
    
$$|\psi\rangle \otimes |\phi\rangle = |\psi\rangle|\phi\rangle = \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix} \otimes 
\begin{bmatrix}
\gamma \\
\delta \\
\end{bmatrix} = 
\begin{bmatrix}
\alpha \begin{bmatrix}
\gamma \\
\delta \\
\end{bmatrix} \\
\beta \begin{bmatrix}
\gamma \\
\delta \\
\end{bmatrix}

\end{bmatrix}$$

<IPython.core.display.Latex object>

In [10]:
%%latex

The inner product is a number, Ex: 1 by 2 matmul 2 by 1 = 1 by 1.

Special case inner product of state vector with its own conjugate transpose.

$$\langle \psi | \psi \rangle = \begin{bmatrix}
\alpha^* & \beta^*
\end{bmatrix} \cdot \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix} = \alpha^*\alpha + \beta^*\beta$$

General case with another $|\phi\rangle = \gamma|0\rangle + \delta|1\rangle$ 

$$\langle \phi | \psi \rangle = \begin{bmatrix}
\gamma^* & \delta^*
\end{bmatrix} \cdot \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix} = \gamma^*\alpha + \delta^*\beta$$

(See N&C section 2.1.4).


<IPython.core.display.Latex object>

In [11]:
%%latex 

The outer product is a matrix (operator).  Ex: 2 by 1 matmul 1 by 2 = 2 by 2.
$$|\psi \rangle \langle \psi | = \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix} \cdot \begin{bmatrix}
\alpha^* & \beta^*
\end{bmatrix} = \begin{bmatrix}
\alpha\alpha^* & \alpha\beta^* \\
\beta\alpha^* & \beta\beta^* \\ \end{bmatrix}$$

<IPython.core.display.Latex object>

In [12]:
%%latex

The Born rule relates amplitude (coefficients) to measurement probabilities.
$$|\alpha|^2 + |\beta|^2 = 1$$

<IPython.core.display.Latex object>

In [13]:
%%latex

State preparation: Assume we can initialize all qubits to $|0\rangle$

<IPython.core.display.Latex object>

In [14]:
%%latex

Quantum gates (operators) are represented by matrices.  E.g. Single qubit Hadamard gate $\mathbf{H}$

$$\mathbf{H} = \frac{1}{\sqrt{2}} \begin{bmatrix}
1 & 1 \\
1 & -1 \\
\end{bmatrix}$$

Operation on basis states:

$$\mathbf{H}|0\rangle = \frac{|0\rangle + |1\rangle}{\sqrt{2}}$$

Exercise: Work out $\mathbf{H}|1\rangle$.

<IPython.core.display.Latex object>

In [15]:
%%latex

Controlled-NOT gate $\mathbf{CNOT}$ 

$$\mathbf{CNOT} = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

## Numpy

In [16]:
ket_0 = np.array([[1],[0]])
ket_1 = np.array([[0],[1]])
ket_0, ket_1

(array([[1],
        [0]]),
 array([[0],
        [1]]))

In [17]:
had = 1/np.sqrt(2) * np.array([[1,1],[1,-1]])
had

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [18]:
np.matmul(had,ket_0), np.matmul(had,ket_1)

(array([[0.70710678],
        [0.70710678]]),
 array([[ 0.70710678],
        [-0.70710678]]))

In [21]:
cnot = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
cnot

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [ ]:
# Apply for sanity checks

In [23]:
# The tensor product corresponds to the Kronecker product 
zero_zero = np.kron(ket_0,ket_0)
zero_zero

array([[1],
       [0],
       [0],
       [0]])

In [24]:
# Gates are matmul
np.matmul(cnot, zero_zero)

array([[1],
       [0],
       [0],
       [0]])

In [25]:
np.kron(ket_1,ket_0), np.matmul(cnot, np.kron(ket_1,ket_0))

(array([[0],
        [0],
        [1],
        [0]]),
 array([[0],
        [0],
        [0],
        [1]]))

In [ ]:
# Exercise: prove CNOT takes 00 to 00, 01 to 01, 10 to 11, 11 to 10

In [ ]:
# Exercise: work out other two cases

In [ ]:
# Extra credit to think about: 
# Compare binary representations of integers with the result of tensor/kronecker on basis states.
# E.g. 6 is represented as 110 in binary.  
# What would a "qubit representation" of 13 be, and what does it look like 
# after expanding the tensor?

In [26]:
%%latex
$$|"13"\rangle = |????\rangle = 
\begin{bmatrix}
? \\
\vdots \\
? \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [ ]:
thirteen = np.kron(ket_1, np.kron(ket_1, np.kron(ket_0,ket_1)))
thirteen

In [ ]:
# Recover the integer!
np.where(thirteen == 1)