In [19]:
# CB: Some qubit basics representated in LaTeX and numpy.
# CB: This is NOT comprehensive in any way.  Just a starting place.
# CB: Note: If writing Dirac notation in a TeX document, please use the braket package!
import numpy as np

In [2]:
%%latex
$$|0\rangle = \begin{bmatrix}
1 \\
0 \\
\end{bmatrix}$$

$$|1\rangle = \begin{bmatrix}
0 \\
1 \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [10]:
%%latex

The state of a qubit with complex coefficients $\alpha$ and $\beta$.

$$|\psi\rangle = \alpha|0\rangle + \beta|1\rangle = \begin{bmatrix}
\alpha \\
0 \\
\end{bmatrix} + \begin{bmatrix}
0 \\
\beta \\
\end{bmatrix} = \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [4]:
%%latex

Conjugate transpose of state vector
$$\langle \psi | = \alpha^*\langle 0| + \beta^*\langle 1| = \begin{bmatrix}
\alpha^* & 0
\end{bmatrix} + \begin{bmatrix}
0 & \beta^*
\end{bmatrix} = \begin{bmatrix}
\alpha^* & \beta^*
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [5]:
%%latex

The inner product is a number.  1 by 2 times 2 by 1 = 1 by 1.

$$\langle \psi | \psi \rangle = \begin{bmatrix}
\alpha^* & \beta^*
\end{bmatrix} \cdot \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix} = \alpha^*\alpha + \beta^*\beta$$

<IPython.core.display.Latex object>

In [6]:
%%latex 

The outer product is a matrix (operator).  2 by 1 times 1 by 2 = 2 by 2.
$$|\psi \rangle \langle \psi | = \begin{bmatrix}
\alpha \\
\beta \\
\end{bmatrix} \cdot \begin{bmatrix}
\alpha^* & \beta^*
\end{bmatrix} = \begin{bmatrix}
\alpha\alpha^* & \alpha\beta^* \\
\beta\alpha^* & \beta\beta^* \\ \end{bmatrix}$$

<IPython.core.display.Latex object>

In [7]:
%%latex

The Born rule relates amplitude (coefficients) to measurement probabilities.
$$|\alpha|^2 + |\beta|^2 = 1$$

<IPython.core.display.Latex object>

In [11]:
%%latex

State preparation: Assume we can initialize all qubits to $|0\rangle$

<IPython.core.display.Latex object>

In [17]:
%%latex

Quantum gates (operators) are represented by matrices.  E.g. Single qubit Hadamard gate $\mathbf{H}$

$$\mathbf{H} = \frac{1}{\sqrt{2}} \begin{bmatrix}
1 & 1 \\
1 & -1 \\
\end{bmatrix}$$

Operation on basis states:

$$\mathbf{H}|0\rangle = \frac{|0\rangle + |1\rangle}{\sqrt{2}}$$

Exercise: Work out $\mathbf{H}|1\rangle$.

<IPython.core.display.Latex object>

In [18]:
%%latex

Controlled-NOT gate $\mathbf{CNOT}$ 

$$\mathbf{CNOT} = \begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0 \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [25]:
ket_0 = np.array([[1],[0]])
ket_1 = np.array([[0],[1]])
ket_0, ket_1

(array([[1],
        [0]]),
 array([[0],
        [1]]))

In [30]:
had = 1/np.sqrt(2) * np.array([[1,1],[1,-1]])
had

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [34]:
np.matmul(had,ket_0), np.matmul(had,ket_1)

(array([[0.70710678],
        [0.70710678]]),
 array([[ 0.70710678],
        [-0.70710678]]))

In [22]:
cnot = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])

In [ ]:
# Apply for sanity checks

In [44]:
np.kron(ket_0,ket_0), np.matmul(cnot, np.kron(ket_0,ket_0))

(array([[1],
        [0],
        [0],
        [0]]),
 array([[1],
        [0],
        [0],
        [0]]))

In [43]:
np.kron(ket_1,ket_0), np.matmul(cnot, np.kron(ket_1,ket_0))

(array([[0],
        [0],
        [1],
        [0]]),
 array([[0],
        [0],
        [0],
        [1]]))

In [45]:
# Exercise: work out other two cases