In [1]:
# CB: Second notebook going over basics of eigenvectors and eigenvalues.
# CB: This follows section 2.1.5 in N&C.
import numpy as np

## Eigenstuff

In [2]:
%%latex

Eigenvector $v$ and eigenvalue $\lambda$ of operator $\mathbf{A}$:
    
$$\mathbf{A}(v) = \lambda v$$

The vector's direction, under operator's action, is unchanged.  The scale/magnitude is the eigenvalue.

Nielsen and Chuang Dirac/quantum computing notation where eigenvalue matches eigenvector:

$$\mathbf{A}|v\rangle = v|v\rangle$$

Since, in computational basis, entries of 1 multiplied by the eigenvalue $\lambda_i$ will just be the eigenvalue, $\lambda_i$.



<IPython.core.display.Latex object>

In [3]:
%%latex

Characteristic function to find eigenvalues.

$$c(\lambda) \equiv det|\mathbf{A} - \lambda\mathbf{I}|$$

<IPython.core.display.Latex object>

In [4]:
%%latex

Example of 2 by 2 determinant:
    
$$det\left(
\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix} 
\right) =
ad - cb

$$


<IPython.core.display.Latex object>

In [5]:
%%latex

Calculate $\mathbf{A} - \lambda\mathbf{I}$

$$\mathbf{A} - \lambda\mathbf{I} = 
\begin{bmatrix}
a & b \\
c & d \\
\end{bmatrix}  - 
\lambda \begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix} =
\begin{bmatrix}
a - \lambda & b \\
c & d - \lambda \\
\end{bmatrix} = 
\mathbf{A_\lambda}
$$

<IPython.core.display.Latex object>

In [6]:
%%latex

Calculate $det(\mathbf{A_\lambda})$

$$det(\mathbf{A_\lambda}) = ?$$

<IPython.core.display.Latex object>

In [7]:
%%latex



$$c(\lambda) = 0$$

Will enable solving to find eigenvalues.  

<IPython.core.display.Latex object>

In [8]:
%%latex

If eigenvectors of a matrix (operator, linear transformation) are unchanged, 
the eigenvectors are found by setting the matrix times unknown vector $v$ equal to zero vector.

$$\mathbf{A_\lambda} v = \mathbf{0}$$

$$\mathbf{A_\lambda} v = \mathbf{A_\lambda} \begin{bmatrix}
x \\
y \\
\end{bmatrix} = \mathbf{0}$$

<IPython.core.display.Latex object>

# Examples: Pauli matrices

In [9]:
%%latex

The Pauli matrices $I, X, Y, Z$ (see N&C 2.1.3) are the following (can also be denoted with $\sigma$):
    
$$\sigma_I = 
\begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix}$$

$$\sigma_x = 
\begin{bmatrix}
0 & 1 \\
1 & 0 \\
\end{bmatrix}$$

$$\sigma_y = 
\begin{bmatrix}
0 & -i \\
i & 0 \\
\end{bmatrix}$$

$$\sigma_z = 
\begin{bmatrix}
1 & 0 \\
0 & -1 \\
\end{bmatrix}$$

<IPython.core.display.Latex object>

In [10]:
# 1.  Create numpy objects representing the Pauli matrices.  

In [11]:
# Here is the identity matrix for you.
sigma_I = np.array([[1,0],[0,1]])
sigma_I

array([[1, 0],
       [0, 1]])

In [12]:
# 2.  Use np.linalg.eig to calculate eigenvalues of Pauli matrices.

In [13]:
np.linalg.eig(sigma_I)

(array([1., 1.]),
 array([[1., 0.],
        [0., 1.]]))

In [14]:
# Compare the result with the documentation, make sure you understand what the function does.
np.linalg.eig?

Signature: np.linalg.eig(a)
Docstring:
Compute the eigenvalues and right eigenvectors of a square array.

Parameters
----------
a : (..., M, M) array
    Matrices for which the eigenvalues and right eigenvectors will
    be computed

Returns
-------
w : (..., M) array
    The eigenvalues, each repeated according to its multiplicity.
    The eigenvalues are not necessarily ordered. The resulting
    array will be of complex type, unless the imaginary part is
    zero in which case it will be cast to a real type. When `a`
    is real the resulting eigenvalues will be real (0 imaginary
    part) or occur in conjugate pairs

v : (..., M, M) array
    The normalized (unit "length") eigenvectors, such that the
    column ``v[:,i]`` is the eigenvector corresponding to the
    eigenvalue ``w[i]``.

Raises
------
LinAlgError
    If the eigenvalue computation does not converge.

See Also
--------
eigvals : eigenvalues of a non-symmetric array.
eigh : eigenvalues and eigenvectors of a real symmet